[versions]
springBoot = "3.2.0"
kotlin = "1.9.21"
ktlintPlugin = "14.2.0"
ktlint = "1.8.0"
kover = "0.7.6"
kotlinLogging = "3.0.5"
resilience4j = "2.2.0"
testcontainers = "1.21.4"

[libraries]
springBootBom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
kotlinLogging = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlinLogging" }
resilience4jSpringBoot3 = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }
resilience4jKotlin = { module = "io.github.resilience4j:resilience4j-kotlin", version.ref = "resilience4j" }
testcontainersJunitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainersCore = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
