[versions]
springBoot = "4.1.0"
kotlin = "2.4.10"
ktlintPlugin = "14.2.0"
ktlint = "1.8.0"
kover = "0.9.9"
kotlinLogging = "8.0.4"
resilience4j = "2.4.0"
testcontainers = "2.0.5"
mockitoKotlin = "4.1.0"
jjwt = "0.12.6"
logstashLogbackEncoder = "8.1"
minio = "8.5.17"

[libraries]
springBootBom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
jacksonKotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
jacksonYaml = { module = "tools.jackson.dataformat:jackson-dataformat-yaml" }
jjwtApi = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwtImpl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwtJackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
logstashLogbackEncoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashLogbackEncoder" }
minio = { module = "io.minio:minio", version.ref = "minio" }
resilience4jSpringBoot4 = { module = "io.github.resilience4j:resilience4j-spring-boot4", version.ref = "resilience4j" }
resilience4jKotlin = { module = "io.github.resilience4j:resilience4j-kotlin", version.ref = "resilience4j" }
testcontainersJunitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainersPostgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
